// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

const sampleProductsNutrition = {
  kcal: 100,
  carbs: 10,
};

const sampleProductsDietary = {
  vegan: false,
  wheatFree: false,
  halal: false,
  nutFree: false,
  glutenFree: false,
};

const sampleProductsReviewSummary = {
  count: 42,
  average: 4.2,
};

const sampleProducts = [
  {
    title: "Onboarding Giftbox with Strong Coffee",
    images: ["brownies-birthday-coffee.webp"],
    priceInPence: 15_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Birthday Mini Giftbox with Fizz",
    images: ["brownies-birthday-fizz-mini.webp"],
    priceInPence: 22_99,
    newIn: true,
    nutrition: { kcal: 900, carbs: 230 },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { count: 4, average: 1 },
  },
  {
    title: "Birthday Giftbox with Fizz",
    images: ["brownies-birthday-fizz.webp"],
    priceInPence: 27_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Birthday Giftbox (wheat-free)",
    images: ["brownies-birthday-wheat-free.webp"],
    priceInPence: 27_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, wheatFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Birthday Giftbox",
    images: ["brownies-birthday.webp"],
    priceInPence: 9_99,
    newIn: false,
    nutrition: { kcal: 920, carbs: 290 },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Classic Chocolate Giftset",
    images: ["brownies-class-chocolate.webp"],
    priceInPence: 7_99,
    newIn: false,
    nutrition: { kcal: 700, carbs: 430 },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Congratulations Giftbox Mixed",
    images: ["brownies-congrats-mixed.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Congratulations Giftbox (wheat-free)",
    images: ["brownies-congrats-wheat-free.webp"],
    priceInPence: 12_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, wheatFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Congratulations Giftbox",
    images: ["brownies-congrats.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { kcal: 820, carbs: 690 },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Eid Mubarak Giftbox (nut-free)",
    images: ["brownies-eid-mubarak-nut-free.webp"],
    priceInPence: 14_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: {
      ...sampleProductsDietary,
      halal: true,
      nutFree: true,
    },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Eid Mubarak Giftbox (wheat-free)",
    images: ["brownies-eid-mubarak-wheat-free.webp"],
    priceInPence: 14_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: {
      ...sampleProductsDietary,
      halal: true,
      wheatFree: true,
    },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Eid Mubarak Giftbox",
    images: ["brownies-eid-mubarak.webp"],
    priceInPence: 14_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, halal: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Fathers Day Giftbox with Beer",
    images: ["brownies-fathers-day-beer.webp"],
    priceInPence: 17_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Fathers Day Giftbox",
    images: ["brownies-fathers-day.webp"],
    priceInPence: 12_99,
    newIn: true,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Birthday Giftbox (nut-free)",
    images: ["brownies-happy-birthday-no-nuts.webp"],
    priceInPence: 11_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, nutFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Love Giftbox (wheat-free)",
    images: ["brownies-love-wheat-free.jpg"],
    priceInPence: 13_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, wheatFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Mixed Giftbox Mini",
    images: ["brownies-mixed-mini.webp"],
    priceInPence: 7_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Thank You Giftbox (no nuts)",
    images: ["brownies-thank-you-no-nuts.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, nutFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Thinking of You Giftbox (no nuts)",
    images: ["brownies-thinking-of-you-no-nuts.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, nutFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Thinking of You Giftbox",
    images: ["brownies-thinking-of-you.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "You're A Star Giftbox (nut-free)",
    images: ["brownies-ur-a-star-no-nuts.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, nutFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "You're A Star Giftbox (vegan, wheat-free)",
    images: ["brownies-ur-a-star-vegan-wheat-free.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, wheatFree: true, vegan: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "You're A Star Giftbox",
    images: ["brownies-ur-a-star.webp"],
    priceInPence: 12_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "Giftbox (vegan, wheat-free)",
    images: ["brownies-vegan-wheat-free.webp"],
    priceInPence: 9_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, wheatFree: true, vegan: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "With Love Giftbox (nuts-free)",
    images: ["brownies-with-love-no-nuts.webp"],
    priceInPence: 11_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary, nutFree: true },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
  {
    title: "With Love Giftbox",
    images: ["brownies-with-love.jpg"],
    priceInPence: 11_99,
    newIn: false,
    nutrition: { ...sampleProductsNutrition },
    dietary: { ...sampleProductsDietary },
    reviewsSummary: { ...sampleProductsReviewSummary },
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json({ products: sampleProducts });
}
